CLUSTER_NAME := trying-out-kubernetes
CLUSTER_REGION := us-central1
CLUSTER_VERSION := 1.12.8-gke.6
HELM_VERSION := 2.13.0
SPINNAKER_SERVICE_ACCOUNT_NAME := spinnaker-storage-account-4
SPINNAKER_VERSION := 1.10.2
SPINNAKER_TIMEOUT := 600
SPINNAKER_CONFIG_FILE := spinnaker-config.yaml
SPINNAKER_SERVICE_ACCOUNT_JSON_FILE := spinnaker-sa.json
SPINNAKER_STORAGE_BUCKET := $(PROJECT_NAME)-cd-config
SPINNAKER_USERNAME := _json_key
SPINNAKER_EMAIL := 1234@5678.com
SPINNAKER_NAMESPACE := spinnaker
SPINNAKER_CHART_VERSION := 1.1.6
SPINNAKER_PORT := 3000
PROJECT_NAME = $(shell gcloud info --format='value(config.project)')
SERVICE_USER = $(shell gcloud config get-value account)
SPINNAKER_SERVICE_ACCOUNT_EMAIL = $(shell gcloud iam service-accounts list --filter="displayName:$(SPINNAKER_SERVICE_ACCOUNT_NAME)" --format='value(email)')
SPINNAKER_DECK_POD = $(shell kubectl get pods --namespace $(SPINNAKER_NAMESPACE) -l "cluster=spin-deck" -o jsonpath="{.items[0].metadata.name}")

.install_helm:
	HELM_VERSION=$(HELM_VERSION) \
	SERVICE_USER=$(SERVICE_USER) \
	./scripts/setup-helm.sh
	touch $@

.install_kubernetes:
	PROJECT_NAME=$(PROJECT_NAME) \
	CLUSTER_NAME=$(CLUSTER_NAME) \
	CLUSTER_REGION=$(CLUSTER_REGION) \
	./scripts/setup-kubernetes.sh
	touch $@

.install_spinnaker:
	PROJECT_NAME=$(PROJECT_NAME) \
	SPINNAKER_CONFIG_FILE=$(SPINNAKER_CONFIG_FILE) \
	SPINNAKER_SERVICE_ACCOUNT_NAME=$(SPINNAKER_SERVICE_ACCOUNT_NAME) \
	SPINNAKER_SERVICE_ACCOUNT_JSON_FILE=$(SPINNAKER_SERVICE_ACCOUNT_JSON_FILE) \
	SPINNAKER_TIMEOUT=$(SPINNAKER_TIMEOUT) \
	SPINNAKER_VERSION=$(SPINNAKER_VERSION) \
	SPINNAKER_STORAGE_BUCKET=$(SPINNAKER_STORAGE_BUCKET) \
	SPINNAKER_USERNAME=$(SPINNAKER_USERNAME) \
	SPINNAKER_EMAIL=$(SPINNAKER_EMAIL) \
	SPINNAKER_CHART_VERSION=$(SPINNAKER_CHART_VERSION) \
	SPINNAKER_NAMESPACE=$(SPINNAKER_NAMESPACE) \
	CLUSTER_REGION=$(CLUSTER_REGION) \
	./scripts/setup-spinnaker.sh
	touch $@

install_dependencies: .install_kubernetes .install_helm .install_spinnaker

setup_port_forwarding:
	SPINNAKER_NAMESPACE=$(SPINNAKER_NAMESPACE) \
	SPINNAKER_DECK_POD=$(SPINNAKER_DECK_POD) \
	SPINNAKER_PORT=$(SPINNAKER_PORT) \
	./scripts/setup-port-forwarding.sh

.remove_install_files:
	rm -rf .install_* .create_*
	rm -rf helm* $(SPINNAKER_CONFIG_FILE) $(SPINNAKER_SERVICE_ACCOUNT_JSON_FILE)

clean: .remove_install_files
	PROJECT_NAME=$(PROJECT_NAME) \
	CLUSTER_NAME=$(CLUSTER_NAME) \
	SPINNAKER_STORAGE_BUCKET=$(SPINNAKER_STORAGE_BUCKET) \
	SPINNAKER_SERVICE_ACCOUNT_EMAIL=$(SPINNAKER_SERVICE_ACCOUNT_EMAIL) \
	CLUSTER_REGION=$(CLUSTER_REGION) \
	./scripts/reset.sh
